version: '3'

services:
  redis:
    image: 'redis:3.2-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  web:
    build: .
    command: >
      gunicorn -c gunicorn.py --reload "hello.app:app"
    depends_on:
      - 'redis'
    environment:
      - REDIS_URL
      - WEB2_COUNTER_MSG
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'

volumes:
  redis: {}
