name: Flask CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: developement
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: start docker compose for databases
      run: docker compose up -d
      timeout-minutes: 5

    - name: Install Doppler CLI and Fetch Secrets
      uses: dopplerhq/cli-action@v1 # Use the official Doppler CLI GitHub Action
      with:
        # This token is a GitHub Repository Secret (NOT an Environment Secret).
        # It's the credential that allows the GitHub Action to talk to Doppler.
        doppler-token: ${{ secrets.DOPPLER_TOKEN }}
        # If your GitHub Environment name is different from your Doppler config name (e.g., 'dev'),
        # you can explicitly specify the Doppler config here:
        doppler-config: dev
        
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: check pre-commit
    #   run: |
    #     pre-commit run --all-files

    - name: Run Tests
      run: |
        python3 -m unittest
