name: Deploy to DigitalOcean App Platform

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Uncommented for better security practices

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Fetch Doppler Secrets (for Deployment, if needed)
        uses: DopplerHQ/secrets-fetch-action@v1.3.0
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true

      - name: Login to DigitalOcean Container Registry
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Build and Push Docker Image to DOCR
        env:
          IMAGE_NAME: github_digital_ocean_doppler_img
          REGISTRY_NAME: registry.digitalocean.com/cognitiveadv
          TAG: ${{ github.sha }}
        run: |
          echo "Building Docker image: ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          docker build -t ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .
          echo "Pushing Docker image to DOCR..."
          docker push ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          echo "Docker image pushed successfully."
          
          # Verify image exists in registry
          echo "Verifying image in registry..."
          doctl registry repository list-tags github_digital_ocean_doppler_img
          
          # Add a small delay to ensure registry consistency
          sleep 30

      - name: Update App Platform Spec with new image tag
        env:
          TAG: ${{ github.sha }}
        run: |
          # echo "Current content of app.yaml:"
          # cat .digitalocean/app.yaml
          
          sed -i "s|\${TAG}|${{ env.TAG }}|g" .digitalocean/app.yaml
          
          # echo "Updated content of app.yaml:"
          # cat .digitalocean/app.yaml

      - name: Create App if not exists
        run: |
          if ! doctl apps list | grep -q "github-digital-ocean-doppler"; then
            echo "Creating new app..."
            doctl apps create --spec .digitalocean/app.yaml
          else
            echo "App already exists"
          fi

      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@v2.0.9
        with:
          app_name: github-digital-ocean-doppler
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          app_spec_location: .digitalocean/app.yaml
          create_app: true 
          print_build_logs: true
          print_deploy_logs: true