name: Build and Push to DOCR

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Fetch Doppler Secrets
        uses: DopplerHQ/secrets-fetch-action@v1.3.0
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true

      - name: Login to DigitalOcean Container Registry
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to Container Registry
        run: doctl registry login --expiry-seconds 1200


      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: github_digital_ocean_doppler_img
          REGISTRY_NAME: registry.digitalocean.com/cognitiveadv
          TAG: ${{ github.sha }}
        run: |
          echo "Building image..."
          # Build with SHA tag
          docker build -t ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .
          # Tag the same image as latest
          docker tag ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest
          
          echo "Pushing images..."
          # Push both tags
          docker push ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          docker push ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest
          
          echo "Images pushed successfully with tags: ${{ env.TAG }} and latest"