name: Deploy to DigitalOcean App Platform

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Uncommented for better security practices

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Fetch Doppler Secrets (for Deployment, if needed)
        uses: DopplerHQ/secrets-fetch-action@v1.3.0
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true

      - name: Login to DigitalOcean Container Registry
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Build and Push Docker Image to DOCR
        env:
          IMAGE_NAME: github_digital_ocean_doppler_img
          REGISTRY_NAME: cognitiveadv
          TAG: ${{ github.sha }}
        run: |
          echo "Building Docker image: registry.digitalocean.com/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          docker build -t registry.digitalocean.com/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .
          echo "Pushing Docker image to DOCR..."
          docker push registry.digitalocean.com/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          echo "Docker image pushed successfully."

      - name: Update App Platform Spec with new image tag
        env:
          TAG: ${{ github.sha }}
        run: |
          sed -i "s|tag: latest|tag: ${{ env.TAG }}|g" .digitalocean/app.yaml
          echo "Updated app.yaml with image tag: ${{ env.TAG }}"

      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@v2.0.9
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          app_spec_location: .digitalocean/app.yaml
          print_build_logs: true
          print_deploy_logs: true

# Kept commented out as they were in original file
#          env: |
#            DATABASE_URL=${{ env.DATABASE_URL }}
#            API_KEY=${{ env.API_KEY }}