name: Pull Request Workflow

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Fetch Doppler Secrets
      uses: DopplerHQ/secrets-fetch-action@v1.3.0
      with:
        doppler-token: ${{ secrets.DOPPLER_TOKEN }}
        inject-env-vars: true

    # - name: start docker compose for databases
    #   run: docker compose up -d
    #   timeout-minutes: 5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.6.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Ruff
      run: ruff check --output-format=github .

    - name: Run Tests
      run: python3 -m unittest
